### ISSUE TITLE
Add cursor to name selection

### ISSUE THREAD

**Issue by lfuelling** [MyRealityCoding/scope#48]
As you can see in the screenshot the name input doesn't show a cursor when active. I don't know if this is intended, but it would be a bit easier to use, if there was a cursor. even a small, static one would be nice.

![bildschirmfoto 2015-12-16 um 09 18 37](https://cloud.githubusercontent.com/assets/5144843/11835754/00dfa7da-a3d6-11e5-88a0-578c367c5ab2.png)

**Comment by bitbrain** [comment]
Hah, I forgot to turn it on. The whole UI will get some love this week (textboxes getting styled etc.) stay tuned, cheers! :+1:

**Comment by bitbrain** [comment]
This problem will be tackled in issue #49.

New design of text boxes and check boxes:
![ui](https://cloud.githubusercontent.com/assets/822035/11840956/2c1bf1aa-a3fa-11e5-854a-df61317ebfbf.png)
