### ISSUE TITLE
Create official soundtrack (OST)

### ISSUE THREAD

**Issue by bitbrain** [MyRealityCoding/scope#9]

**Comment by lfuelling** [comment]
I finished the main theme/menu song. 
I'm unsure whether this is a bit too ambient or just enough. So please tell me what you think of it.

(Pushing in a few secs)

**Comment by bitbrain** [comment]
@lfuelling I like the music. When 1:00 kicks in (with the melody and the acid), it's perfect! Since the music starts early (when loading resources already) I would prefer in the beginning a more ambient setup (without hi-hat and maybe even no drums, just ambient and a melody). To achieve the "infinite loop effect" the track could become more ambient and drum-less at the end again to fit to the beginning.

Overall feeling is perfect! :tada: :tada:

**Comment by lfuelling** [comment]
Awesome! :3

The only "melody" like thing  I used is some of those chord things so I'll just stick to that.

**Comment by lfuelling** [comment]
I've updated the song again. Now with more pads at the beginning and the Hi-Hats starting after 32 beats.

I'm unsure whether the ending is good now. I removed the bass drum but left the hihats in (and the fadeout too).

**Comment by bitbrain** [comment]
Perfect. :+1:
